# Generated by Django 6.0.6 on 2026-06-13 15:53

import django
import django.db.models.deletion
from django.db import migrations, models

# CheckConstraint's keyword was renamed `check` -> `condition` in Django 5.1.
_CHECK_KW = 'condition' if django.VERSION >= (5, 1) else 'check'


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_si', models.CharField(max_length=255)),
                ('name_ta', models.CharField(max_length=255)),
                ('department_en', models.CharField(max_length=255)),
                ('department_si', models.CharField(max_length=255)),
                ('department_ta', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('hospital', 'Hospitals'), ('police', 'Police'), ('court', 'Courts'), ('school', 'Schools'), ('government', 'Government'), ('transport', 'Transport'), ('post', 'Post Office')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('address_en', models.TextField()),
                ('address_si', models.TextField()),
                ('address_ta', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('website', models.URLField(blank=True, max_length=1024, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_always_open', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='services.service')),
            ],
            options={
                'db_table': 'opening_hours',
            },
        ),
        migrations.CreateModel(
            name='ServicePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=100)),
                ('label_si', models.CharField(max_length=100)),
                ('label_ta', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='services.service')),
            ],
            options={
                'db_table': 'service_phones',
            },
        ),
        migrations.CreateModel(
            name='OpeningHourSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='services.openinghours')),
            ],
            options={
                'db_table': 'opening_hour_slots',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('hours', 'weekday'), name='one_slot_per_weekday'), models.CheckConstraint(name='close_after_open', **{_CHECK_KW: models.Q(('close_time__gt', models.F('open_time')))})],
            },
        ),
    ]
