# Generated by Django 6.0.6 on 2026-06-12 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_si', models.CharField(max_length=255)),
                ('name_ta', models.CharField(max_length=255)),
                ('department_en', models.CharField(max_length=255)),
                ('department_si', models.CharField(max_length=255)),
                ('department_ta', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hospital', 'Hospital'), ('police', 'Police'), ('post_office', 'Post Office'), ('divisional_secretariat', 'Divisional Secretariat'), ('grama_niladhari', 'Grama Niladhari'), ('agrarian', 'Agrarian Services'), ('water_board', 'Water Board'), ('electricity_board', 'Electricity Board'), ('other', 'Other')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('address_en', models.TextField()),
                ('address_si', models.TextField()),
                ('address_ta', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('website', models.URLField(blank=True, max_length=1024, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_always_open', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mon', models.CharField(blank=True, max_length=20, null=True)),
                ('tue', models.CharField(blank=True, max_length=20, null=True)),
                ('wed', models.CharField(blank=True, max_length=20, null=True)),
                ('thu', models.CharField(blank=True, max_length=20, null=True)),
                ('fri', models.CharField(blank=True, max_length=20, null=True)),
                ('sat', models.CharField(blank=True, max_length=20, null=True)),
                ('sun', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='services.service')),
            ],
            options={
                'db_table': 'opening_hours',
            },
        ),
        migrations.CreateModel(
            name='ServicePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=100)),
                ('label_si', models.CharField(max_length=100)),
                ('label_ta', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='services.service')),
            ],
            options={
                'db_table': 'service_phones',
            },
        ),
    ]
