# Generated by Django 6.0.6 on 2026-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('hospital', 'Hospitals'), ('police', 'Police'), ('court', 'Courts'), ('school', 'Schools'), ('government', 'Government'), ('transport', 'Transport'), ('post', 'Post Office')], max_length=50),
        ),
    ]
