# Generated by Django 5.0.4 on 2026-06-13 17:02

import django.db.models.deletion
from django.db import migrations, models


def seed_categories(apps, schema_editor):
    Category = apps.get_model('services', 'Category')
    Service = apps.get_model('services', 'Service')
    # Get unique category codes from existing services just to be safe
    existing_codes = Service.objects.values_list('category', flat=True).distinct()
    default_names = {
        'electricity': 'Electricity',
        'water': 'Water',
        'hospital': 'Hospitals',
        'police': 'Police',
        'court': 'Courts',
        'school': 'Schools',
        'government': 'Government',
        'transport': 'Transport',
        'post': 'Post Office',
    }
    for code in existing_codes:
        if not Category.objects.filter(code=code).exists():
            Category.objects.create(
                code=code,
                name_en=default_names.get(code, code.title()),
                name_si=default_names.get(code, code.title()),
                name_ta=default_names.get(code, code.title())
            )

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_si', models.CharField(max_length=100)),
                ('name_ta', models.CharField(max_length=100)),
                ('icon', models.CharField(default='account_balance_outlined', max_length=50)),
                ('color', models.CharField(default='0xFF0F6E56', max_length=10)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.RunPython(seed_categories, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.RESTRICT, to='services.category'),
        ),
    ]
