# Generated by Django 6.0.6 on 2026-06-12 19:16

import django
import django.db.models.deletion
from django.db import migrations, models

# CheckConstraint's keyword was renamed `check` -> `condition` in Django 5.1.
_CHECK_KW = 'condition' if django.VERSION >= (5, 1) else 'check'


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='wed',
        ),
        migrations.CreateModel(
            name='OpeningHourSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='services.openinghours')),
            ],
            options={
                'db_table': 'opening_hour_slots',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('hours', 'weekday'), name='one_slot_per_weekday'), models.CheckConstraint(name='close_after_open', **{_CHECK_KW: models.Q(('close_time__gt', models.F('open_time')))})],
            },
        ),
    ]
