# Generated by Django 6.0.6 on 2026-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyHotline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=16)),
                ('icon_key', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=7)),
                ('is_quick_dial', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'emergency_hotlines',
                'ordering': ['sort_order'],
            },
        ),
    ]
